### ISSUE TITLE
change to allow unpriv user to model Postgres DBs

### ISSUE THREAD

**Issue by davidmmiller** [epuzanov/ZenPacks.community.PgSQLMon#1]
With an unpriv user - i.e. one without any grants or superuser privs - the modelling of Postgres databases fails for me.

Within PgSqlDatabaseMap.py on line 64 - if I replace pg_authid with pg_roles, then an unpriv user can run the modelling queries.

See this for more details on the pg_roles view - http://www.postgresql.org/docs/8.3/static/view-pg-roles.html

**Comment by epuzanov** [comment]
Thanks, fixed.
